obj-m += hookPacketFilter.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

ins:
	sudo dmesg -C
	sudo insmod hookPacketFilter.ko

rm:
	sudo rmmod hookPacketFilter

