obj-m += preventing_ping.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

ins:
	sudo dmesg -C
	sudo insmod preventing_ping.o

rm:
	sudo rmmod preventing_ping.c

